
package ed;

import ed.estructuras.lineales.*;
import java.util.ArrayList;
import java.util.List;

public class Prueba{
    public static void main(String[] args){
        ArrayList<String> lista1 = new ArrayList<>();
        lista1.add("a");
        lista1.add("b");
        lista1.add("c");
        lista1.add("d");
        lista1.add("e");
        ListaDoblementeLigada<String> modelo = new ListaDoblementeLigada<>(lista1);
        System.out.println("Se crea una lista a partr de otra colección con 5 elementos:\n"+modelo.toString());
        modelo.add("f");
        System.out.println("Se agrega f al final de la lista.\n"+modelo.toString());
        modelo.add(2, "x");
        System.out.println("Se agrega una x en la posición 2:");
        System.out.println(modelo.toString());
        int sizemenos2 = modelo.size()-2;
        modelo.add(sizemenos2, "y");
        System.out.println("Se agrega una y en la posición "+sizemenos2);
        System.out.println(modelo.toString());
        lista1.clear();
        lista1.add("g");
        lista1.add("h");
        lista1.add("i");
        modelo.addAll(lista1);
        System.out.println("Se le concatena la lista:"+lista1.toString());
        System.out.println(modelo.toString());
        lista1.remove("i");
        modelo.addAll(4, lista1);
        System.out.println("Se agrega la lista "+lista1.toString()+" en la posición 4.");
        System.out.println(modelo);
        modelo.clear();
        System.out.println("Se vacía la lista:\n"+modelo.toString());
        modelo.add("a");
        modelo.add("t");
        modelo.add("i");
        modelo.add("n");
        modelo.add("o");
        modelo.add("b");
        modelo.add("o");
        modelo.add("n");
        modelo.add("i");
        modelo.add("t");
        modelo.add("a");
        System.out.println("Se le agrega una oración palíndroma:\n"+modelo.toString());
        System.out.println("Se verifica si contiene la letra: a (se espera true)");
        System.out.println(modelo.contains("a"));
        lista1.clear();
        lista1.add("a");
        lista1.add("b");
        lista1.add("n");
        System.out.println("Se verifica si contiene los elementos de la lista "+lista1.toString()+" (se espera true)");
        System.out.println(modelo.containsAll(lista1));
        ListaDoblementeLigada<String> lista2 = new ListaDoblementeLigada<>(modelo);
        System.out.println("Se verifica si es igual a "+lista2+" (se espera true)");
        System.out.println(modelo.equals(lista2));
        System.out.println("Se obtiene al elemento en la posición 3 (se espera n)");
        System.out.println(modelo.get(3));
        System.out.println("Se obtiene el código hash de esta lista.");
        System.out.println(modelo.hashCode());
        System.out.println("Se obtiene al primer índice de i (se espera 2)");
        System.out.println(modelo.indexOf("i"));
        System.out.println("Se obtiene al último índice de i (se espera 8)");
        System.out.println(modelo.lastIndexOf("i"));
        System.out.println("Se comprueba si está vacía (se espera false)");
        System.out.println(modelo.isEmpty());
        System.out.println("Se elimina al elemento en la posición 5");
        System.out.println("Eliminado: "+modelo.remove(5));
        System.out.println(modelo);
        System.out.println("Elimina la primera aparición de a:");
        modelo.remove("a");
        System.out.println(modelo);
        lista1.clear();
        lista1.add("a");
        lista1.add("t");
        lista1.add("n");
        System.out.println("Se eliminan a todos los elementos que aparezcan en la lista: "+lista1.toString());
        modelo.removeAll(lista1);
        System.out.println(modelo);
        lista1.clear();
        lista1.add("o");
        lista1.add("z");
        System.out.println("Se retienen solo los elementos que aparecen en la lista: "+lista1.toString());
        modelo.retainAll(lista1);
        System.out.println(modelo);
        System.out.println("Se reemplaza el elemento en la posición 1 por p.");
        modelo.set(1, "p");
        System.out.println(modelo);
        System.out.println("Se agregan las letras de la q a la v.");
        modelo.add("q");
        modelo.add("r");
        modelo.add("s");
        modelo.add("t");
        modelo.add("u");
        modelo.add("v");
        System.out.println(modelo);
        System.out.println("Se obtiene una sublista de 2 (inclusivo) a 5 (exclusivo).");
        List<String> sl = modelo.subList(2,5);
        System.out.println(sl);
    }
}
